### ISSUE TITLE
Provide binaries

### ISSUE THREAD

**Issue by nlamirault** [ncabatoff/dbms_exporter#7]
Hi,
could you provide binaires like on your others projects (https://github.com/ncabatoff/process-exporter/releases/tag/v0.5.0)
Thanks.

**Comment by ncabatoff** [comment]
Yup, it's been on my TODO list for a long time.  I've put it off until now because I didn't have a good way to test the releases, but now that I do it shouldn't take long.

**Comment by ncabatoff** [comment]
Finally got the release pipeline working!  So now when I push a git tag, assuming it builds and tests pass a release will automatically be created on both github and docker hub.  

Release [v0.0.2](https://github.com/ncabatoff/dbms_exporter/releases/tag/v0.0.2) is out now, which is basically the same code that's been there for years, plus your PR.  

Now I'll work on running integration tests as part of the release process.  I wanted to do that first but I also didn't want to leave you hanging so I decided to defer it.

**Comment by nlamirault** [comment]
Why not a 0.1.0 release ? or 0.2.0 ?
Using Semver ...

**Comment by ncabatoff** [comment]
I plan to do that after the integration tests are done.  v0.0.2 was a compromise just to get something out there you could use.  Since this has been in constant use on over a thousand hosts for years (thanks to my previous employer) I feel that it's actually pretty mature and probably due for a 1.0 soon, but let's start with 0.1.0.
