### ISSUE TITLE
Binary with freedts driver ?

### ISSUE THREAD

**Issue by nlamirault** [ncabatoff/dbms_exporter#8]
Hi,
I just tried to use the binary of the release, but I have an error on the driver "freedts" 

```bash
time="2019-05-10T07:27:27Z" level=fatal msg="driver \"freetds\" not supported in this build" source="dbms_exporter.go:488"
```
Command line : `/usr/local/bin/dbms_exporter -driver sybase -queryfile /etc/sybase.yaml`

What about provide binary files with different built-in drivers?

**Comment by ncabatoff** [comment]
Hi @nlamirault,

It turns out that I had bugs in my build process which resulted in no drivers being compiled in.  I thought I'd tested properly but evidently not.  The good news is I've fixed them and finally implemented the CI tests that verify a build before I release it.  Please try v0.1.0 and let me know if you have any problems.

**Comment by nlamirault** [comment]
@ncabatoff Release 0.1.0 works fine. Thanks
